foodle/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('select2/', include('django_select2.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('profile/<int:user_id>/', views.view_profile, name='profile'),
    path('stores/', views.stores_index, name='index'),
    path('stores/<str:store_name>/detail/',
         views.stores_detail, name='detail'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('checkout/<int:user_id>/', views.checkout, name='checkout'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/signup/volunteer',
         views.volunteer_signup, name='volunteer_signup'),
    path('cart/<int:user_id>/', views.cart, name='cart'),
    path('customer/edit/',views.edit_profile, name="customer_update"),
    path('volunteer/edit/',views.edit_volunteer_profile, name="edit_volunteer_profile"),
    path('customer/password/',views.change_password, name="change_password"),
    path('volunteer/password/',views.change_volunteer_password, name="change_volunteer_password"),
    path('volunteer/<int:user_id>/add_photo/',
         views.add_photo, name="add_photo"),
    path('add_delivery_time/<int:user_id>/<int:volunteer_id>/',
         views.cart, name='add_timeslot'),
    path('cart/<int:user_id>/assoc_item/<int:item_id>/',
         views.assoc_item, name='assoc_item'),
    path('cart/<int:user_id>/disassoc_item/<int:item_id>/', views.disassoc_item, name='disassoc_item'),
    path('stores/<str:store_name>/detail/<int:user_id>/disassoc_item_in_store/<int:item_id>/', views.disassoc_item_in_store, name='disassoc_item_in_store'),
    path('checkout/delivery/',views.select_delivery, name="select_delivery"),
    path('complete_order/',views.add_delivery, name="complete_order"),
    path('checkout/thankyou/',views.thank_you, name="thankyou"),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User
from multiselectfield import MultiSelectField

UNITS = (
    ('E', 'Each'),
    ('L', 'LB'),
    ('O', 'OZ'),
    ('F', 'FL OZ'),
    ('U', 'Unit'),
    ('G', 'Gram'),
    ('K', 'KG'),
    ('M', 'GL'),
    ('D', 'Dozen')
)

TIMESLOTS = (
    ("A",	"9AM–10AM"),
    ("B",	"10AM–11AM"),
    ("C",	"11AM–12PM"),
    ("D",	"12PM–1PM"),
    ("E",	"1PM–2PM"),
    ("F",	"2PM–3PM"),
    ("G",	"3PM–4PM"),
    ("H",	"4PM–5PM"),
    ("I",	"5PM–6PM"),
    ("J",	"6PM–7PM"),
    ("K",	"7PM–8PM"),
    ("L",	"8PM–9PM"),
    ("M",	"9PM–10PM")
)


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    delivery_time = MultiSelectField(	
        max_length=100, null=True, choices=TIMESLOTS, max_choices=3)
        # MultiSelectField(max_length=100, null=True, choices=TIMESLOTS, max_choices=3)

    def get_absolute_url(self):
        return reverse('checkout', kwargs={'customer_id': self.id})

    def get_absolute_url(self):
        return reverse('profile')

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

class CustomerDelivery(models.Model):
  date = models.DateField(verbose_name='Delivery date')
  delivery_time = models.CharField(
        max_length=1,
        choices=TIMESLOTS,
        default=TIMESLOTS[0][0]) 
  
  customer = models.ForeignKey(Customer, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_delivery_time_display()} on {self.date}"

  class Meta:
    ordering = ['date']

class Volunteer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    availability_date = models.DateField(
        verbose_name='available date', null=True)
    availability = MultiSelectField(max_length=100, choices=TIMESLOTS)

    customer = models.ManyToManyField(Customer, through="Timeslot")

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"


class Timeslot(models.Model):
    date = models.DateField()
    timeslot = models.CharField(
        verbose_name="Timeslot",
        max_length=1,
        choices=TIMESLOTS,
        default=TIMESLOTS[0][0])

    def __str__(self):
        return f"{self.date} at {self.get_timeslot_display()}"

    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    volunteer = models.ForeignKey(Volunteer, on_delete=models.CASCADE)


class Store(models.Model):
    name = models.CharField(max_length=50)
    location = models.CharField(max_length=100, null=True)
    image = models.CharField(verbose_name="Image URL",
                             max_length=1000, null=True)

    def __str__(self):
        return f"{self.name}"


class Item(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    unit_price = models.FloatField("Price")
    unit_measurement = models.CharField(
        verbose_name="Measurement Units",
        max_length=1,
        choices=UNITS,
        default=UNITS[0][0])
    image = models.CharField(verbose_name="Image URL", max_length=1000)
    item_count = models.IntegerField(null=True)
    count_ref = models.IntegerField(default=1, null=True)

    store = models.ForeignKey(Store, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} at ${self.unit_price}/{self.get_unit_measurement_display()}"

    def line_total(self):
        return (self.count_ref * self.unit_price)


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(Item)
    order_date = models.DateTimeField(auto_now=True)
    is_ordered = models.BooleanField(default=False)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.unit_price for item in self.items.all()])

    def __str__(self):
        if self.items.count() == 1:
            return f"{self.user.first_name}'s cart has {self.items.count()} item"
        else:
            return f"{self.user.first_name}'s cart has {self.items.count()} items"


class Photo(models.Model):
    url = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for user_id: {self.user_id} @{self.url}"


class LineItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.DecimalField(
        decimal_places=2,
        max_digits=6)

main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import Group
from django.urls import reverse
from datetime import date


from .scraper import walmart_fruit
from . forms import CustomerSignUpForm, VolunteerSignUpForm, UserUpdateForm, EditCustomerForm, EditVolunteerForm, EditVolunteerAvailablityForm, AddDeliveryTimeForm
from .models import Item, Cart, Timeslot, Customer, Volunteer, User, Store, Photo, CustomerDelivery
from .decorators import allowed_users

import uuid
import boto3


S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'foodle'


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = CustomerSignUpForm(request.POST)
        if form.is_valid():
            group = Group.objects.get(name='customer')
            print(group)
            user = form.save()
            customer_profile = Customer(user=user)
            cart = Cart(user=user)
            cart.save()
            customer_profile.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user.groups.add(group)
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            user_id = user.id
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    form = CustomerSignUpForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


def volunteer_signup(request):
    error_message = ''
    if request.method == 'POST':
        form = VolunteerSignUpForm(request.POST)
        for time in form:
            print(time)
        if form.is_valid():
            group = Group.objects.get(name='volunteer')
            # print(group)
            user = form.save()
            volunteer_profile = Volunteer(user=user)
            print(volunteer_profile)
            volunteer_profile.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user.groups.add(group)
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            user_id = user.id
            return redirect('profile', user_id=user_id)
        else:
            error_message = 'Invalid sign up - try again'
    form = VolunteerSignUpForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup_volunteer.html', context)


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


@login_required
@allowed_users(allowed_roles=['customer'])
def stores_index(request):
    stores = Store.objects.all()

    context = {'stores': stores}
    return render(request, 'stores/index.html', context)


@login_required
@allowed_users(allowed_roles=['customer'])
def stores_detail(request, store_name):
    customer = Customer.objects.filter(user=request.user)
    cart = Cart.objects.filter(user=request.user).all()
    user_group = str(request.user.groups.all()[0])
    stores = Store.objects.all()
    store = stores.filter(name=store_name).first()
    items = Item.objects.filter(store=store)
    product_total = 0
    store_item = None
    for obj in cart:
        for product in obj.items.all():
            item = Item.objects.filter(id=product.id)
            piece = item.first()
            store_item = piece.store.name
            prices = round(piece.unit_price, 2)
            if product.store == store:
                product_total += piece.count_ref * prices
    context = {'items': items, 'store': store, 'user_group': user_group, 'customer': customer,
               'cart': cart, 'product_total': round(product_total, 2), 'store_item': store_item}
    return render(request, 'stores/detail.html', context)


def logout(request):
    return render(request, 'home.html')


@login_required
@allowed_users(allowed_roles=['customer'])
def checkout(request, user_id):
    error_message = ''
    customer = Customer.objects.filter(user=request.user).first()
    active_customer_cart = Cart.objects.filter(user=request.user).first()
    all_volunteers = Volunteer.objects.all()
    customer_delivery_time = CustomerDelivery.objects.filter(date=date.today(), customer=customer)
    delivery = None
    delivery_date = None
    time_value = None
    for time in customer_delivery_time:
        delivery = time.get_delivery_time_display()
        delivery_date = time.date
        time_value = time.delivery_time
    if delivery != None:
        for volunteer in all_volunteers:
            if delivery in volunteer.get_availability_display() and delivery_date == volunteer.availability_date:
                print(volunteer)
                volunteer.availability
                volunteer.availability_date
                timeslot = Timeslot(date=delivery_date, customer=customer, volunteer=volunteer, timeslot=time_value)
                existing_timeslots = Timeslot.objects.all()
                print(existing_timeslots.exists())
                if existing_timeslots.exists():
                    for time in existing_timeslots:
                        print(time.timeslot)
                        print(timeslot.timeslot)
                        if (time.timeslot == timeslot.timeslot) and (time.date == timeslot.date) and (time.customer.id == timeslot.customer.id) and (time.volunteer.id == timeslot.volunteer.id):
                            print('exists')
                            error_message = 'Sorry No Volunteers Are Available To Deliver At That Time. Please Select Another Time'
                            context = {'error': error_message}
                            return render(request, 'checkout.html', context)
                        else:
                            timeslot.save()
                            current_timeslot = Timeslot.objects.first()
                            active_customer_cart.delete()
                            cart = Cart(user=request.user)
                            cart.save()
                            context = {'customer': customer, 'timeslot': current_timeslot, 'vol_time': volunteer}
                            return redirect('/checkout/thankyou')
                else:
                    timeslot.save()
                    current_timeslot = Timeslot.objects.first()
                    active_customer_cart.delete()
                    cart = Cart(user=request.user)
                    cart.save()
                    context = {'customer': customer, 'timeslot': current_timeslot, 'vol_time': volunteer}
                    return redirect('/checkout/thankyou')

    else:
        error_message = 'Sorry No Volunteers Are Available To Deliver At This Time'
        print(error_message)
        context = {'error': error_message}
        return render(request, 'checkout.html', context)
    error_message = 'Sorry No Volunteers Are Available To Deliver At This Time'
    context = {'error': error_message}
    return render(request, 'checkout.html', context)


@login_required
def thank_you(request):
    customer = Customer.objects.filter(user=request.user)
    timeslot = Timeslot.objects.filter(customer=customer.first())
    context = {'customer': customer, 'timeslot': timeslot}
    return render(request, 'checkout/thankyou.html', context)


@login_required
@allowed_users(allowed_roles=['customer'])
def cart(request, user_id):
    customer = Customer.objects.filter(user=request.user)
    cart = Cart.objects.filter(user=request.user).all()
    user_group = str(request.user.groups.all()[0])
    product_total = 0
    store_item = None
    for obj in cart:
        for product in obj.items.all():
            item = Item.objects.filter(id=product.id)
            piece = item.first()
            store_item = piece.store.name
            prices = round(piece.unit_price, 2)
            product_total += piece.count_ref * prices
    context = {'user_group': user_group, 'customer': customer,
               'cart': cart, 'product_total': round(product_total, 2), 'store_item': store_item}
    return render(request, 'account/cart.html', context)


def view_profile(request, user_id, *kwargs):
    all_customer = Customer.objects.all()
    one_customer = Customer.objects.filter(user=request.user)
    one_volunteer = Volunteer.objects.filter(user=request.user)
    all_volunteer = Volunteer.objects.all()
    print(one_customer, one_volunteer)
    photo = Photo.objects.filter(user=request.user)
    vol = None
    for person in all_volunteer:
        vol = person

    vol_timeslot = Timeslot.objects.filter(volunteer__in=all_volunteer)
    cus_timeslot = Timeslot.objects.filter(customer__in=one_customer)

    context = {'user_id': user_id, 'one_customer': one_customer, 'one_volunteer': one_volunteer, 'all_customer': all_customer,
               'all_volunteer': all_volunteer, 'vol_timeslot': vol_timeslot, 'cus_timeslot': cus_timeslot, 'photo': photo}
    return render(request, 'account/profile.html', context)


@login_required
def edit_profile(request):
    user_id = request.user.id
    if request.method == 'POST':
        form = EditCustomerForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile', user_id=user_id)
    else:
        form = EditCustomerForm(instance=request.user)
        context = {'form': form}

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h3>About Foodle</h3>
<main class="about-container">
    <p>Foodle is a grocery delivery app that was inspired to be a solution during the COVID-19 pandemic.
        In our current state of COVID-19, social distancing has made it difficult for more at risk populations to buy
        groceries in a timely manner.
        We wanted to create an app where a person could order groceriesfrom a store, and have them delivered by a
        volunteer.
    </p>

    <p>With Foodle you can be apart of something bigger than by becoming a volunteer to help serve those in need.
        Our volunteers are our most important piece to our day to day operations. Without them Foodle wouldn't be able
        to reach the many that need nourishment and other supplies during this tough time.
    </p>
</main>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>Foodle | Volunteer powered delivery</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  {% block css %}
  <!-- Compiled and minified CSS -->
  <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css"
    integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
  {% endblock css %}
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  {{ form.media.css }}
  <script defer src="{% static 'js/script.js'%}"></script>
</head>

<body>
  {% block javascript %}
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js"
    integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

  <script>
    $(document).ready(function () {
      for (let i = 0; i >= 12; i++) {
        $(`#id_delivery_time_${i}`).formSelect();
      }

    });
    $(document).ready(function () {
      // Initialize materialize data picker
      $("#id_availability_date").datepicker({ format: "yyyy-mm-dd" });
      $("select").formSelect();
      $('div.browser-default').removeClass('browser-default')
      // $("#id_delivery_time").formSelect();
    });
  </script>
  {% endblock javascript %}
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper navbar">
        <ul>
          <li>
            <a href="/">
              <img class="foodle-logo" src="{% static 'images/foodle_logo.svg'%}" alt="logo" />
            </a>
          </li>
        </ul>
        <ul class="right">
          {% if user.is_authenticated %}
          <!-- <li><a href="{% url 'checkout' user.id %}">Checkout</a></li> -->
          <ul id="dropdown1" class="dropdown-content" style="overflow:hidden;">
            <li style="background-color:#5085a5; color: #f7f9fb; max-width: 300px;"><a class="white-text"
                style="width: 300px; line-height: 50px;" href="#">Welcome, {{user.first_name}}!</a></li>
            <li><a href="/about">About</a></li>
            <li><a href="{% url 'profile' user.id %}">Profile</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
          </ul>
          <li>
            <a class="dropdown-trigger" href="#" data-target="dropdown1">Welcome, {{user.first_name}}!</a>
          </li>
          {% if user.customer %}
          <li><a href="{% url 'index' %}">Stores</a></li>
          <li><a href="{% url 'cart' user.id %}"><i class="large material-icons" id="openModal">shopping_cart</i></a>
          </li>
          {% endif %}
          {% else %}
          <li><a href="{% url 'login' %}">Log In</a></li>
          <!-- <li><a href="{% url 'signup' %}">Sign Up</a></li> -->
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="main-container container">

    {% block content %} {% endblock %}
  </main>
  <footer class="page-footer footer">
    <div class="center">
      All Rights Reserved, &copy; {% now "Y" %} Foodle &nbsp;
    </div>
  </footer>
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      var elems = document.querySelectorAll(".dropdown-trigger");
      var instances = M.Dropdown.init(elems);
    });
  </script>
</body>

</html>

main_app/templates/checkout.html
{% extends 'base.html' %}

{% block content %}
{% if error%}
<h1 class="center">Checkout Page</h1>
<div style="border: 2px solid #000; border-radius: 10px; background-color: rgb(238, 138, 138); width: 40rem; height: 30rem; color: #fff; margin: 10rem 10rem 1rem 10rem; display: flex; justify-content: center; align-items: center;">
  <h3 style="text-align: center;">
    {{ error}}
  </h3>
</div>
<a class="btn" href="{% url 'select_delivery' %}" style="margin-bottom: 3rem; display: flex; justify-content: center;">Select a Different Time</a>
{% endif %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="home-container">
    <h2>Welcome to Foodle!</h2>
    <div>
      {% load static %}
        <img src="{% static "source.gif" %}" alt="My image">
    </div>
    <div class="login-choice">
        <div style="display: flex;">
          <a style="padding: 1rem; height: 4rem; font-size: medium;" class="btn blue" href="{% url 'volunteer_signup' %}">Sign up as a Volunteer</a>
          <a style="padding: 1rem; height: 4rem; font-size: medium;" class="btn blue" href="{% url 'signup' %}">Sign up as a Customer</a>
      </div>
    </div>
  </div>

{% endblock %}